[phases.setup]
nixPkgs = ['nodejs', 'yarn', 'python39', 'gcc']

[phases.install]
cmds = ['python -m venv /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt', 'cd client && yarn install']

[phases.build]
cmds = ['cd client && yarn build']

[start]
cmd = "gunicorn main:app"